### ISSUE TITLE
Comments / suggestions

### ISSUE THREAD

**Issue by justinlittman** [vivo-community/vivo-docker2#1]
Here's a few minor comments / suggestions:
1. At https://github.com/awoods/vivo-docker2/blob/master/solr/Dockerfile#L1, I'd recommend selecting a specific tag.
2. At https://github.com/awoods/vivo-docker2/blob/master/docker-compose.yml#L17, if you're going to have your own image, might as well put the command in the Dockerfile rather than docker-compose.

I was able to get both images running.

**Comment by awoods** [comment]
Thanks, @justinlittman .
Regarding your point (2.), it was not clear to me how to include the `command` in the Dockerfile. Suggestions?

**Comment by justinlittman** [comment]
Last line of your Dockerfile would be:
```
CMD solr-create -c vivocore -d /opt/vivocore
```
or 
```
CMD ["solr-create", "-c", "vivocore", "-d", "/opt/vivocore"]
```
