### ISSUE TITLE
Vivo docker installation fails looking for http://solr:8983/solr/vivocore

### ISSUE THREAD

**Issue by jcabrerazuniga** [vivo-community/vivo-docker2#22]
The vivo installation process using Docker containers created the docker containers using the vivo_vivo docker network:

CONTAINER ID   IMAGE                                COMMAND                  CREATED             STATUS             PORTS                                       NAMES
d3407d95233b   vivoweb/vivo-solr:latest             "docker-entrypoint.s…"   About an hour ago   Up About an hour   0.0.0.0:8983->8983/tcp, :::8983->8983/tcp   vivo-solr-1
7ecb5a6e5ac0   vivo-tomcat                          "/bin/bash /start.sh"    About an hour ago   Up About an hour   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   vivo

This creates an error where vivo was looking for http://solr:8983 

FATAL: ApplicationImpl$ComponentsSetup

    Could not set up the Solr search engine
    edu.cornell.mannlib.vitro.webapp.application.ApplicationImpl$ComponentsSetup

    org.apache.solr.client.solrj.SolrServerException: Server refused connection at: http://solr:8983/solr/vivocore
    	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:650)
    	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:255)
    	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:244)
    	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:194)
    	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:942)
    	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:957)
    	at edu.cornell.mannlib.vitro.webapp.searchengine.solr.SolrFieldInitializer.excludeMatched

so I had to rename the vivo-solr-1 container

docker container rename vivo-solr-1 solr

this allowed Vivo docker to start after stopping it.

**Comment by chenejac** [comment]
@jcabrerazuniga thanks for reporting this issue. However, this project is not so active at the moment, we moved instantization of Docker to the [VIVO project codebase](https://github.com/vivo-project/VIVO). Can you please try to create a Docker container from there, and if there is some issue, open a GitHub issue at https://github.com/vivo-project/VIVO/issues?
